name = "sb-slash"
type = "webpack"
account_id = "d5ccf1d783709bbdc23fc29786f38736"
workers_dev = true
webpack_config = "webpack.config.js"
kv_namespaces = [
  { binding = "NAMESPACE", id="fa509cd9887c42df8967b891d4cb420a" }
]
compatibility_date = "2022-02-17"