name: Deploy
on: [pull_request, workflow_dispatch]

jobs:
  deploy:
    uses: mchangrh/actions/.github/workflows/cf-worker.yml@main
    with:
      environment: dev
    secrets:
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }} 