name: Update interactions
on: [workflow_dispatch]

jobs:
  update-interactions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install deps
        run: npm ci
      - name: Update interactions
        env:
          CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
          BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          CLIENT_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
        run: | 
          mkdir build/build/data
          npm run build